export const projects = [
    {id: 1, title: "Backroads App", 
    desc: "", 
    img: "", 
    links: {github: "", url: ""}},
    {id: 2, title: "Birthday App", 
    desc: "", 
    img: "", 
    links: {github: "", url: ""}},
    {id: 3, title: "Countries", 
    desc: "", 
    img: "", 
    links: {github: "", url: ""}},
    {id: 4, title: "Spotify Profile", 
    desc: "", 
    img: "", 
    links: {github: "", url: ""}},
    {id: 5, title: "Color Generator", 
    desc: "This is a simple color generator app built with React. It allows you to generate random colors and copy their hexadecimal values to use in your projects.", 
    img: "", 
    links: {github: "", url: ""}},
] 